language: python

sudo: false
dist: xenial

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

python:
  - "3.7"
  - "3.6"

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install
  - poetry build

script: poetry run pytest

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    tags: true
