language: python

sudo: false
dist: xenial

os: osx
language: generic
env: PYTHON=3.6.0
install:
  - brew update
  - brew install openssl readline
  - brew outdated pyenv || brew upgrade pyenv
  - brew install pyenv-virtualenv
  - eval "$(pyenv init -)"
  - pyenv install $PYTHON
  - pyenv virtualenv $PYTHON travis
  - pyenv activate travis
  - python --version
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install
script:
  - python -c "import sys; print(sys.maxsize)"
  - python -c "print(int(0))"
  - python -c "print(int(2147483646))"
  - python -c "print(int(2147483647))"
  - python -c "print(int(2147483648))"
  - python -c "print(int(2147483649))"
  - python -c "print(int(9223372036854775806))"
  - python -c "print(int(9223372036854775807))"
  - python -c "print(int(9223372036854775808))"
  - python -c "print(int(9223372036854775809))"
  - python -c "print(int(0) in range(-2147483647, 2147483647))"
  - python -c "print(int(0) in range(-2147483648, 2147483648))"
  - python -c "print(int(0) in range(-2147483649, 2147483649))"
  - python -c "print(int(0) in range(-9223372036854775807, 9223372036854775807))"
  - python -c "print(int(0) in range(-9223372036854775808, 9223372036854775808))"
  - python -c "print(int(0) in range(-9223372036854775809, 9223372036854775809))"
  - poetry run pytest
