sudo: false
dist: xenial
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - poetry install -v
  - poetry build -v
script: poetry run pytest
